### ISSUE TITLE
大佬 问个问题

### ISSUE THREAD

**Issue by Kodak00sec** [yj94/BinarySpy#4]
![微信图片_20240903170114](https://github.com/user-attachments/assets/cc5ad932-1261-48c4-816a-bfba76f87c2a)
大佬 提醒这个是白文件的问题还是payload的问题呀

**Comment by yj94** [comment]
提示这个就再点一下fuzz

**Comment by Kodak00sec** [comment]
> 提示这个就再点一下fuzz

再点一下 还是提示这个呢

**Comment by yj94** [comment]
白文件文件吧

**Comment by Kodak00sec** [comment]
> 提示这个就再点一下fuzz

再点的话 没有生成新的EXE程序 是因为白文件用的不对吗

**Comment by Kodak00sec** [comment]
> 白文件文件吧

大佬 请问一下 哪一类的白文件是可以用的呢？

**Comment by yj94** [comment]
不要用release版本的，用源代码 python BinarySpy.py 运行 可以提示报错的，可以知道哪里出问题了。

**Comment by Kodak00sec** [comment]
> 不要用release版本的，用源代码 python BinarySpy.py 运行 可以提示报错的，可以知道哪里出问题了。

好的 感谢
