### ISSUE TITLE
函数开头特征问题

### ISSUE THREAD

**Issue by lz520520** [yj94/BinarySpy#5]
我看readme中写了push ebp rbp，sub esp rsp作为开头特征，但IDA分析中，我基本没看到这样的开头特征，这个是怎么提取的

**Comment by yj94** [comment]
有的呀，具体实现原理都在代码里面了，你说的操作栈的特征我没具体使用，作为学习案例罢了，我使用的是insn.mnemonic == 'call' or insn.mnemonic == 'jmp'来找函数调用，然后他的操作地址直接作为patch函数地址了，然后找ret计算一下之间大小，总之就是很粗糙的方法，使用栈操作的函数非常多，所以本文提到的只是举个例子，还是找call和jmp好一些！
